### ISSUE TITLE
Feature req: 拉取数据时，设置默认时区

### ISSUE THREAD

**Issue by uiosun** [zhangbc97/tushare-integration#11]
clickhouse server 没有设置 timezone 的情况下，拉取的数据直接当作 UTC 填入

 - 考虑是否为数据主动添加时区；
 - 考虑是否在文档上注明这一点，以提醒使用者。

> Tips: If who need the information: 
> The DBeaver will show server time (default UTC), but when you run select or filter, your input WHERE filter is CST or local time (auto convert to UTC)

**Comment by uiosun** [comment]
`tushare_integration/pipelines.py:122`
```python
        if (primary_key := self.schema.get("primary_key", None)) is not None and len(primary_key) > 0:
            data = data.drop_duplicates(subset=primary_key, keep="last")
            if "trade_time" in primary_key:
                # 自动检测时间字段并将其转换为CST时区
                for col in data.columns:
                    if data[col].dtypes == 'datetime64[ns]':
                        data[col] = data[col].dt.tz_localize('Asia/Shanghai')
```

Hi，@zhangbc97 不知道你这边的 PR 有什么要求，简单的解决方案是自动处理一下时间（也可以抽成外部配置），附在这里。

这里只针对分钟线做了处理

**Comment by zhangbc97** [comment]
感谢反馈，对于PR没有额外要求，欢迎提交PR，合并后我来发布新版本~

**Comment by uiosun** [comment]
好，稍晚些提 PR。近期有点忙，在用 go 写自研的量化研究框架。

感觉工程化的模式，这个 issue 应该改写成：

1. 数据源/配置文件，支持定义时区
2. 数据管道应该读取时区配置、时间字段，自动转换对应数据

**Comment by zhangbc97** [comment]
https://github.com/zhangbc97/tushare-integration/pull/12#issue-2647853455
